name: Generate Snake Game

on:
  schedule: 
    - cron: "0 */12 * * *"  # Runs every 12 hours
  workflow_dispatch:

permissions:
  contents: write  # Allows writing to the repo
  pages: write
  id-token: write

jobs:
  build:
    name: Jobs to update data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Generate Snake Animation
      - name: Generate Snake Animation
        uses: Sutil/snk@master
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-contribution-grid-snake.svg
          snake_color: "blue"

      # Deploy to Output Branch
      - name: Deploy to Output Branch
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output  # Ensure this branch exists
          build_dir: dist  # This is where the animation is stored
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
